---
- name: Setup ADLIN Server
  hosts: adlin
  remote_user: '{{ ansible_user }}'
  vars_prompt:
    - name: ansible_password
      prompt: "Password"
  roles:
    - role: vault
      tags:
        - vault
    - role: dns
      tags:
        - dns
    - role: webserver
      tags:
        - webserver
    - role: supervision
      tags:
        - supervision