---

- name: Copy bind9 options
  ansible.builtin.template:
    src: files/named.conf.options.j2
    dest: "{{ bind_static_dir }}/named.conf.options"
    owner: bind
    group: bind
    mode: 0664
  become: true
  notify: restart bind9

- name: Copy bind9 zone
  ansible.builtin.template:
    src: files/db.21.srs.adlin.j2
    dest: "{{ bind_dynamic_dir }}/db.21.srs.adlin"
    owner: bind
    group: bind
    mode: 0664
    force: no
  become: true
  notify: restart bind9

- name: Copy bind9 local
  ansible.builtin.template:
    src: files/named.conf.local.j2
    dest: "{{ bind_static_dir }}/named.conf.local"
    owner: root
    group: root
    mode: 0664
  become: true
  notify: restart bind9

- name: Copy key file
  template:
    src: files/keys.j2
    dest: "{{ bind_static_dir }}/keys"
    owner: bind
    group: bind
    mode: 0600
  become: true
  notify: restart bind9

- name: Copy bind9 conf
  ansible.builtin.copy:
    src: files/named.conf
    dest: "{{ bind_static_dir }}/named.conf"
    owner: bind
    group: bind
    mode: 0664
  become: true
  notify: restart bind9

- name: Enable bind9
  become: true
  service:
    name: bind9
    enabled: yes
    state: started

