---

- name: Install packages
  apt:
    state: present
    name:
      - nginx
      - nginx-extras
      - certbot
      - python3-certbot-nginx
  become: true

- name: copy root ca
  become: true
  copy:
    src: "files/adlin-rootCA.crt"
    dest: "/usr/local/share/ca-certificates/adlin/"
  notify: update ca
