---

- name: copy root ca
  become: true
  copy:
    src: "files/adlin-rootCA.crt"
    dest: "/usr/local/share/ca-certificates/adlin/"
  notify: update ca

- name: Check if HTTPS is already enabled
  ansible.builtin.uri:
    url: "https://{{ item }}"
  loop: "{{ domains }}"
  register: https_check
  ignore_errors: true

- name: certbot
  become: true
  command: "certbot --nginx --server {{ ca_server }} -n --agree-tos --email {{ certbot_email }} --domains {{ ','.join(domains) }} --expand"
  when: https_check is failed
